Add Signing Command for use in dUSD
ArdanaLabs/yubihsm-ed-sign pull request #21
Opened 2022-08-31 13:28 UTC by Geometer1729

Closes #20 

The issue says server but we decided a cli was a better plan

This pr will add support to sign txs with a signing command

2022-10-04 14:16 UTC, epiro-ps approved these changes
Looks fantastic. Just a few things - would love to see cabal testing added to the nix flake checks, some documentation, and some clean-up.

2022-10-04 14:16 UTC, epiro-ps commented on flake.nix
>    outputs = { self, nixpkgs, nci, ... }@inputs:
Could we add a checks attribute here that runs `cabal test` so that CI checks for passing tests on build?

2022-10-04 14:16 UTC, epiro-ps commented on app/Main.hs
> +    ["getpubkey"] -> getPK >>= putStrLn
Could we camel case this - `getPubKey`?

2022-10-04 14:16 UTC, epiro-ps commented on src/Api.hs
> +  -- https://github.com/Emurgo/cardano-serialization-lib/blob/e4ae8728a79f77a25c70026bb4fdd4d567a9a20e/rust/src/chain_crypto/algorithms/ed25519.rs#L54
Some docs blocks above these functions for doc gen would be nice.

2022-10-04 14:16 UTC, epiro-ps commented on tests/Main.hs
> +
Might want to clean up all this white-space.

2022-10-04 14:16 UTC, epiro-ps commented on tests/Main.hs
> +
Same here.

2022-10-04 14:21 UTC, epiro-ps requested changes
Meant to block merge with change request.

2022-10-05 15:14 UTC, Geometer1729 commented on flake.nix
>    outputs = { self, nixpkgs, nci, ... }@inputs:
@epiro-ps they seem to already be in CI
https://hercules-ci.com/accounts/github/ArdanaLabs/derivations/%2Fnix%2Fstore%2F7bpz8p6zmadn9lpl3scdmyw3yyqfx4qm-yubihsm-ed-sign-0.1.0.0.drv/log?via-job=181b24bf-63ff-4e9e-bd65-a3fdd64d5e55

2022-10-05 16:35 UTC, epiro-ps approved these changes
Nice mergeable work here. Here's the ticket for the follow up configuration work to ensure this can be run as dummy and on hardware.

https://github.com/ArdanaLabs/yubihsm-ed-sign/issues/23

2022-10-05 16:36 UTC, merged